import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import { ThemeProvider } from "@/context/ThemeContext";
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import { Suspense } from 'react'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
        <ThemeProvider>
          <AuthProvider>
        <div className="container">
      <Navbar></Navbar>
        {children}
        <Footer></Footer>
        </div>
        </AuthProvider>
        </ThemeProvider>
        </Suspense>
        </body>
    </html>
  );
}
